## Tensores en Pytorch

Los tensores permiten manejar en Pytorch estructuras multidimensionales con datos numéricos. Entre otras cosas permiten:

    - Crear tensores con un número arbitrario de dimensiones
        - Inicializándolos con unos valores predefinidos
        - A partir de un ndarray de numpy
        - Emulando la forma de otro tensor o estructura de datos
    - Manipular los tensores
        - Modificando alguna de sus partes de forma selectiva
        - Cambiando su forma
        - Combinando varios tensores
    - Operar tensores
        - Con otros tensores
        - Con escalares
        - In-place
    - Localizar los tensores y su operación en distintos tipos de dispositivos
    - Hacer seguimiento del gradiente de los tensores

***

# Comprobación de la instalación de Pytorch

In [7]:
import torch
import numpy as np

print("== Versión de Pytorch ==")
print(torch.__version__)

== Versión de Pytorch ==
2.2.0+cu121


# Creación e inicialización de tensores

In [2]:

# Creación de tensores desde datos
tensor_from_list = torch.tensor([1, 2, 3])
tensor_from_numpy = torch.from_numpy(np.array([1, 2, 3]))
print("== Creación de tensores desde datos ==")
print(tensor_from_list)
print(tensor_from_numpy)

# Inicialización de tensores
tensor_zeros = torch.zeros(2, 2)
tensor_ones = torch.ones(2, 2)
tensor_random = torch.rand(2, 2)
print("== Inicialización de tensores ==")
print(tensor_zeros)
print(tensor_ones)
print(tensor_random)

# Tensores más complejos
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print("== Tensores más complejos ==")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")
torch.set_printoptions(precision=2)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

# Especificación de tipo de dato y dispositivo
tensor_float = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor_gpu = torch.tensor([1, 2, 3], device="cuda")
print("== Especificación de tipo de dato y dispositivo ==")
print(tensor_float.dtype)
print(tensor_gpu.device)


== Creación de tensores desde datos ==
tensor([1, 2, 3])
tensor([1, 2, 3])
== Inicialización de tensores ==
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6137, 0.8065],
        [0.6509, 0.6309]])
== Tensores más complejos ==
Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
tensor([[0.50, 0.21, 0.28],
        [0.52, 0.23, 0.26]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


RuntimeError: No CUDA GPUs are available

# Operación de tensores

In [3]:
# Operaciones básicas
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

add = a + b
sub = a - b
mul = a * b
div = a / b

# Operaciones matriciales
A = torch.rand(2, 3)
B = torch.rand(3, 4)
matmul = torch.matmul(A, B)
transpose = A.t()
a.mul_(2)
print("== Operaciones matriciales ==")
print(A)
print(B)
print(matmul)
print(transpose)
print("== Operaciones in-place ==")
A.mul_(2)
print(A)

# Cambiar forma de un tensor
A_reshaped = A.view(3, 2)
A_squeezed = A.unsqueeze(0)
A_unsqueezed = A_squeezed.squeeze(0)
print("== Cambiar forma de un tensor ==")
print(A_reshaped)
print(A_squeezed)
print(A_unsqueezed)

# Indexación
first_element = a[0]
first_two_elements = a[:2]
print("== Indexación ==")
print(first_element)
print(first_two_elements)


== Operaciones matriciales ==
tensor([[0.63, 0.85, 1.00],
        [0.26, 0.31, 0.21]])
tensor([[0.62, 0.01, 0.32, 0.07],
        [0.85, 0.88, 0.98, 0.79],
        [0.85, 0.39, 0.41, 0.44]])
tensor([[1.95, 1.14, 1.44, 1.15],
        [0.61, 0.36, 0.48, 0.36]])
tensor([[0.63, 0.26],
        [0.85, 0.31],
        [1.00, 0.21]])
== Operaciones in-place ==
tensor([[1.27, 1.70, 1.99],
        [0.53, 0.63, 0.42]])
== Cambiar forma de un tensor ==
tensor([[1.27, 1.70],
        [1.99, 0.53],
        [0.63, 0.42]])
tensor([[[1.27, 1.70, 1.99],
         [0.53, 0.63, 0.42]]])
tensor([[1.27, 1.70, 1.99],
        [0.53, 0.63, 0.42]])
== Indexación ==
tensor(2)
tensor([2, 4])


# Ubicando un tensor en un dispositivo

In [4]:
# Comprobando si hay GPU disponible
is_cuda_available = torch.cuda.is_available()

# Moviendo tensores a GPU
if is_cuda_available:
    a_gpu = a.to("cuda")
    b_gpu = b.to("cuda")

# Realizando operaciones en GPU
if is_cuda_available:
    add_gpu = a_gpu + b_gpu


# Ejercicio 1

Quita los comentarios y completa las partes relevantes siguiendo las indicaciones

In [5]:
# Importamos PyTorch
import torch

# -----------------------------------------------------------
# Crear un Tensor en PyTorch
# -----------------------------------------------------------
# Crea un tensor de tamaño 5x5 lleno de unos.

# ESCRIBE TU CÓDIGO AQUÍ
# one_tensor = ...

# Imprime tu tensor
# print(one_tensor)


# -----------------------------------------------------------
# Operaciones con Tensores
# -----------------------------------------------------------
# Crea un tensor de tamaño 5x5 lleno de unos y un tensor de tamaño 5x5 lleno de ceros.
# Suma ambos tensores y almacena el resultado en una nueva variable.

# ESCRIBE TU CÓDIGO AQUÍ
# one_tensor = ...
# zeros_tensor = ...  
# sum_tensor = ...

# Imprime tu nuevo tensor
# print(sum_tensor)


# -----------------------------------------------------------
# Ejercicio 3: Redimensionar Tensores
# -----------------------------------------------------------
# Crea un tensor de tamaño 1x25 y redimensionalo a un tamaño de 5x5.

# ESCRIBE TU CÓDIGO AQUÍ
# original_tensor = ...
# reshaped_tensor = ...

# Imprime el tensor redimensionado
# print(reshaped_tensor)


# -----------------------------------------------------------
# Operaciones de Reducción
# -----------------------------------------------------------
# Crea un tensor de tamaño 5x5 con números aleatorios.
# Calcula la suma y la media de los valores del tensor.

# ESCRIBE TU CÓDIGO AQUÍ
# random_tensor = ...
# sum_val = ...
# mean_val = ...

# Imprime los valores de suma y media
# print("Suma:", sum_val)
# print("Media:", mean_val)


# -----------------------------------------------------------
# Propagación de Operaciones
# -----------------------------------------------------------
# Crea dos tensores de tamaño 5x5 llenos de unos.
# Multiplica uno de los tensores por 5.
# Suma ambos tensores y almacena el resultado en un nuevo tensor.

# ESCRIBE TU CÓDIGO AQUÍ
# one_tensor = ...
# another_tensor = ...
# another_tensor = ...
# sum_tensor = ...

# Imprime el resultado de la suma
# print(sum_tensor)

# -----------------------------------------------------------
# Combinar torch.cat y torch.stack
# -----------------------------------------------------------
# Crea dos tensores de tamaño 2x3 llenos de unos y de dos, respectivamente.
# Primero, concatena los dos tensores a lo largo de la segunda dimensión (dim=1).
# Luego, apila los dos tensores originales a lo largo de una nueva dimensión al principio.
# Finalmente, compara las formas de los tensores resultantes.

# ESCRIBE TU CÓDIGO AQUÍ
# tensor1 = ...
# tensor2 = ...
# cat_result = ...
# stack_result = ...

# Imprime los tensores resultantes y sus formas
# print("cat_result:", cat_result, ", shape:", cat_result.shape)
# print("stack_result:", stack_result, ", shape:", stack_result.shape)


# Ejercicio 2

Completa las partes relevantes siguiendo las indicaciones

In [6]:
import torch
from PIL import Image
import numpy as np
import torchvision.transforms as T
from IPython.display import display

def displayT(timg):
    transform = T.ToPILImage()
    img = transform(timg)
    display(img)

# timg representa una imagen con 3 canales (RGB) de 128x128
timg=torch.zeros(3,128,128)
transform = T.ToPILImage()
# Si todos los canales tienen un 0, la imagen es negra
# Si todos los canales tienen un 1, la imagen es blanca
# Si el canal 0 tiene un 1 y los canales 1 y 2 tienen un 0, la imagen es roja
# Si el canal 1 tiene un 1 y los canales 0 y 2 tienen un 0, la imagen es verde
# Si el canal 2 tiene un 1 y los canales 0 y 1 tienen un 0, la imagen es azul
# Si los canales 0 y 1 tienesn un 1 y el canal 2 tiene un 0, la imagen es amarilla
# Si los tres canales tienen un 1, la imagen es blanca
# Imprimimos la imagen inicial: negra
displayT(timg)


# Pinta toda la imagen de rojo
# ESCRIBE TU CÓDIGO AQUÍ
# timg[0,:,:]= ...
print("Imagen roja")
displayT(timg)

# Pinta toda la imagen de amarillo
# ESCRIBE TU CÓDIGO AQUÍ
# timg[1,:,:]= ... 
print("Imagen amarilla")
displayT(timg)

# Pinta una ralla vertical al medio, de dos píxeles de grosor, de color blanco
# ESCRIBE TU CÓDIGO AQUÍ
# timg[2,:,63:65]= ...
print("Imagen con ralla vertical blanca")
displayT(timg)

# Pinta una ralla horizontal al medio, de dos píxeles de grosor, de color blanco
# ESCRIBE TU CÓDIGO AQUÍ
# timg[2,63:65,:]= ...
print("Imagen con rallas vertical y horizontal blancas")
displayT(timg)

ModuleNotFoundError: No module named 'PIL'